/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author etero
 */
public class GastoCalorico extends javax.swing.JFrame {

    /**
     * Creates new form GastoCalorico
     */
    public GastoCalorico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LabelTitle = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        RadioMulher = new javax.swing.JRadioButton();
        RadioHomem = new javax.swing.JRadioButton();
        LabelPeso = new javax.swing.JLabel();
        LabelAltura = new javax.swing.JLabel();
        LabelIdade = new javax.swing.JLabel();
        LabelAtividade = new javax.swing.JLabel();
        InputPeso = new javax.swing.JTextField();
        InputAltura = new javax.swing.JTextField();
        InputIdade = new javax.swing.JTextField();
        ComboAtividade = new javax.swing.JComboBox<>();
        BotaoCalcular = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        LabelGastoBasal = new javax.swing.JLabel();
        LabelGastoTotalFinal = new javax.swing.JLabel();
        LabelGastoBasalFinal = new javax.swing.JLabel();
        LabelGastoTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LabelTitle.setText("Cálculo de gasto calórico");

        jInternalFrame1.setVisible(true);

        buttonGroup1.add(RadioMulher);
        RadioMulher.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        RadioMulher.setText("Mulher");
        RadioMulher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMulherActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioHomem);
        RadioHomem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        RadioHomem.setText("Homem");
        RadioHomem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioHomemActionPerformed(evt);
            }
        });

        LabelPeso.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabelPeso.setText("Peso (kg):");

        LabelAltura.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabelAltura.setText("Altura (cm):");

        LabelIdade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabelIdade.setText("Idade:");

        LabelAtividade.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabelAtividade.setText("Nível de atividade:");

        ComboAtividade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedentário", "Leve", "Moderado", "Ativo", "Extremamente ativo" }));
        ComboAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAtividadeActionPerformed(evt);
            }
        });

        BotaoCalcular.setText("Calcular");
        BotaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(RadioMulher)
                        .addGap(33, 33, 33)
                        .addComponent(RadioHomem))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(InputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(LabelPeso)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(InputPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelAtividade)
                                    .addComponent(LabelIdade, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelAltura, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InputIdade)
                                    .addComponent(ComboAtividade, 0, 186, Short.MAX_VALUE)
                                    .addComponent(BotaoCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioMulher)
                    .addComponent(RadioHomem))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPeso)
                    .addComponent(InputPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAltura)
                    .addComponent(InputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIdade)
                    .addComponent(InputIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAtividade)
                    .addComponent(ComboAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jInternalFrame2.setVisible(true);

        LabelGastoBasal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabelGastoBasal.setText("Gasto basal:");

        LabelGastoTotalFinal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabelGastoTotalFinal.setText(" ");

        LabelGastoBasalFinal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabelGastoBasalFinal.setText(" ");

        LabelGastoTotal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LabelGastoTotal.setText("Gasto total:");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelGastoBasal)
                    .addComponent(LabelGastoTotal))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelGastoBasalFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelGastoTotalFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGastoBasal)
                    .addComponent(LabelGastoBasalFinal))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelGastoTotal)
                    .addComponent(LabelGastoTotalFinal))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jInternalFrame1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(LabelTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jInternalFrame2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCalcularActionPerformed
        String strPeso = InputPeso.getText();
        String strAltura = InputAltura.getText();
        String strIdade = InputIdade.getText();
        
        if ((!RadioHomem.isSelected() && !RadioMulher.isSelected()) || strPeso.isEmpty() || strAltura.isEmpty() || strIdade.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.");       
        }
        
        if (!strPeso.matches("[0-9]{1,3}") || !strAltura.matches("[0-2][.][0-9]{1,2}") || !strIdade.matches("[0-9]{1,3}")) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos com formato coerente.");       
        }
        
        else {
            double peso = Double.parseDouble(strPeso);
        
            double altura = Double.parseDouble(strAltura);

            double idade = Double.parseDouble(strIdade);

            String atividade = ComboAtividade.getSelectedItem().toString();
            Double valorAtividade = 0.0;

            if (atividade == "Sedentário") valorAtividade = 1.2;
            if (atividade == "Leve") valorAtividade = 1.375;
            if (atividade == "Moderado") valorAtividade = 1.55;
            if (atividade == "Ativo") valorAtividade = 1.725;
            if (atividade == "Extremamente Ativo") valorAtividade = 1.9;


            if (RadioHomem.isSelected()) {
                double gastoCalorico = (66 + (13.8 * peso) + (5 * altura) - (6.8 * idade));
                String gastoCaloricoResultado = String.valueOf(gastoCalorico);
                LabelGastoBasalFinal.setText(gastoCaloricoResultado);

                double gastoTotal = gastoCalorico * valorAtividade;
                String gastoTotalResultado = String.valueOf(gastoTotal);
                LabelGastoTotalFinal.setText(gastoTotalResultado);
            }

            else {
                double gastoCalorico = (655 + (9.6 * peso) + (1.9 * altura) - (4.7 * idade));
                String gastoCaloricoResultado = String.valueOf(gastoCalorico);
                LabelGastoBasalFinal.setText(gastoCaloricoResultado); 

                double gastoTotal = gastoCalorico * valorAtividade;
                String gastoTotalResultado = String.valueOf(gastoTotal);
                LabelGastoTotalFinal.setText(gastoTotalResultado);
            }
        }
        
  
    }//GEN-LAST:event_BotaoCalcularActionPerformed

    private void ComboAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAtividadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboAtividadeActionPerformed

    private void RadioHomemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioHomemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioHomemActionPerformed

    private void RadioMulherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMulherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioMulherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GastoCalorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GastoCalorico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCalcular;
    private javax.swing.JComboBox<String> ComboAtividade;
    private javax.swing.JTextField InputAltura;
    private javax.swing.JTextField InputIdade;
    private javax.swing.JTextField InputPeso;
    private javax.swing.JLabel LabelAltura;
    private javax.swing.JLabel LabelAtividade;
    private javax.swing.JLabel LabelGastoBasal;
    private javax.swing.JLabel LabelGastoBasalFinal;
    private javax.swing.JLabel LabelGastoTotal;
    private javax.swing.JLabel LabelGastoTotalFinal;
    private javax.swing.JLabel LabelIdade;
    private javax.swing.JLabel LabelPeso;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JRadioButton RadioHomem;
    private javax.swing.JRadioButton RadioMulher;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
