/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author etero
 */
public class IMC extends javax.swing.JFrame {
    Home home;
    /**
     * Creates new form IMC
     */
    public IMC(Home home) {
        this.home = home;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelTitle = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        LabelPeso = new javax.swing.JLabel();
        LabelAltura1 = new javax.swing.JLabel();
        InputPeso = new javax.swing.JTextField();
        InputAltura = new javax.swing.JTextField();
        ButtonCalcular = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        LabelResultado = new javax.swing.JLabel();
        LabelInterpretacao = new javax.swing.JLabel();
        LabelResultadoFinal = new javax.swing.JLabel();
        LabelInterpretacaoFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        LabelTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        LabelTitle.setText("Cálculo de IMC");

        jInternalFrame1.setVisible(true);

        LabelPeso.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        LabelPeso.setText("Peso (kg):");

        LabelAltura1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        LabelAltura1.setText("Altura (m):");

        InputPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputPesoActionPerformed(evt);
            }
        });

        InputAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAlturaActionPerformed(evt);
            }
        });

        ButtonCalcular.setText("Calcular");
        ButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap(182, Short.MAX_VALUE)
                        .addComponent(InputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(LabelPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputPeso)
                            .addComponent(ButtonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(LabelAltura1)
                    .addContainerGap(284, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPeso)
                    .addComponent(InputPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(ButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(LabelAltura1)
                    .addContainerGap(168, Short.MAX_VALUE)))
        );

        jInternalFrame2.setVisible(true);

        LabelResultado.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        LabelResultado.setText("Resultado:");

        LabelInterpretacao.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        LabelInterpretacao.setText("Interpretação:");

        LabelResultadoFinal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        LabelResultadoFinal.setText(" ");

        LabelInterpretacaoFinal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        LabelInterpretacaoFinal.setText(" ");

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(LabelInterpretacao)
                        .addGap(18, 18, 18)
                        .addComponent(LabelInterpretacaoFinal))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(LabelResultado)
                        .addGap(18, 18, 18)
                        .addComponent(LabelResultadoFinal)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelResultado)
                    .addComponent(LabelResultadoFinal))
                .addGap(25, 25, 25)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelInterpretacao)
                    .addComponent(LabelInterpretacaoFinal))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelTitle)
                    .addComponent(jInternalFrame1)
                    .addComponent(jInternalFrame2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LabelTitle)
                .addGap(18, 18, 18)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPesoActionPerformed

    private void ButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCalcularActionPerformed
        
        
        String strAltura = InputAltura.getText();
        String strPeso = InputPeso.getText();
        
        if (strAltura.isEmpty() && strPeso.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos.");
        }
        
        else if (!(strAltura.matches("[0-2][.][0-9]{1,2}")) || !(strPeso.matches("[0-9]{1,3}"))) {
            JOptionPane.showMessageDialog(null, "Valor inválido! Você deve inserir apenas números em formatos coerentes.");
        }
        
        else {
            float altura = Float.parseFloat(strAltura);
            float peso = Float.parseFloat(strPeso);
        
            float imc = peso / (altura * altura);
            String imcResultado = String.valueOf(imc);
            LabelResultadoFinal.setText(imcResultado);
                    
            if (imc < 18.5) {
                LabelInterpretacaoFinal.setText("Magreza");
            }
        
            else if (imc >= 18.5 && imc <= 24.9) {
                LabelInterpretacaoFinal.setText("Normal");
            }

            else if (imc >= 25 && imc <= 29.9) {
                LabelInterpretacaoFinal.setText("Sobrepeso");
            }        

            else if (imc >= 30 && imc <= 39.9) {
                LabelInterpretacaoFinal.setText("Obesidade");
            }

            else if (imc >= 40) {
                LabelInterpretacaoFinal.setText("Obesidade grave");
            }
        }

      
        
    }//GEN-LAST:event_ButtonCalcularActionPerformed

    private void InputAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAlturaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Home home = new Home();
                new IMC(home).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCalcular;
    private javax.swing.JTextField InputAltura;
    private javax.swing.JTextField InputPeso;
    private javax.swing.JLabel LabelAltura1;
    private javax.swing.JLabel LabelInterpretacao;
    private javax.swing.JLabel LabelInterpretacaoFinal;
    private javax.swing.JLabel LabelPeso;
    private javax.swing.JLabel LabelResultado;
    private javax.swing.JLabel LabelResultadoFinal;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
